### ISSUE TITLE
Laravel-echo-server support?

### ISSUE THREAD

**Issue by djfurman** [happyDemon/vue-echo#1]
Good evening. I'm interested in running some prototypes with echo and vue and came across your project. The documentation mentions the pusher driver, but I'm a DIY fan. Does the package support the [laravel community socket.io version](https://github.com/tlaverdure/laravel-echo-server) ?

If not, are you interested in pull requests to add the functionality?

**Comment by happyDemon** [comment]
@djfurman this package actually injects a working Echo instance into Vue.
All you have to do is change the config when initialising.

``` js
Vue.use(VueEcho, {
    broadcaster: 'socket.io',
    host: 'URL',
});
```

Or as you can see, define an echo instance that gets injected:

``` js
import Echo from 'laravel-echo';

let EchoInstance = new Echo({
     broadcaster: 'socket.io',
    host: 'URL',
});
Vue.use(VueEcho, EchoInstance);
```

Don't forget to include the socket io lib though

**Comment by djfurman** [comment]
Great! Thank you, @happyDemon. I see where the reader says "inject a working echo instance" now. I'm still too green with Echo to realize the implication 😜

**Comment by vesper8** [comment]
is there a benefit to doing it the 2nd way (injection) vs the first way?

And when you say don't forget to include the socket io library, is simply having <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script> in the head of every page sufficient?

I got this to work properly using Laravel Echo strictly in my Laravel app but now struggling to get it to work on a vue client on another server

**Comment by happyDemon** [comment]
@vesper8

I included the option incase anyone would have a need for it (e.g. drop in a replacement lib with a similar api). or if you wanted to be more verbose.

including the library anywhere should be enough.

Be sure to allow the other server to connect to your socket IO server (I think you can do this with the origins option [google search](https://www.google.be/search?q=socket+io+allow+cross+domain&oq=socket+io+allow)

In all honesty it's been a while since I actually setup a socket IO server myself, it might be better to ask around [here](https://github.com/tlaverdure/laravel-echo-server)
