### ISSUE TITLE
I do not know how to output in the browser console

### ISSUE THREAD

**Issue by vxhly** [happyDemon/vue-echo#16]
`main.js`
![image](https://user-images.githubusercontent.com/17906558/33884125-78cbfbaa-df79-11e7-8e42-1b89ddde1447.png)
`App.vue`
![image](https://user-images.githubusercontent.com/17906558/33884196-b5dd395a-df79-11e7-87fe-826c374076fe.png)
In the network you can see the accepted message
![image](https://user-images.githubusercontent.com/17906558/33884239-e11187ac-df79-11e7-86a2-5d94dcd05d97.png)
But there is no console
Send a message in https://dashboard.pusher.com 
![image](https://user-images.githubusercontent.com/17906558/33884386-63641cec-df7a-11e7-90b6-b5f98a49af2c.png)

**Comment by gstvr** [comment]
Hi there!
This is an issue with `laravel-echo`, rather than with this dependency.

I experienced the same problem and managed to fix it.
My event was located at `App\Events\SomeEvent` and my JS code was `this.$echo.private('...').listen('SomeEvent')`. However, I had to set the namespace when initialising Laravel Echo.

```
Vue.use(VueEcho, {
    ...
    namespace: 'App.Events'
})
```

That fixed my problem and I hope this does fix yours as well!
