### ISSUE TITLE
Pusher is not defined

### ISSUE THREAD

**Issue by salvationarinze** [happyDemon/vue-echo#25]
Hi,
Nice package. I followed the installation instructions documented and it breaks the app with the log message `Pusher not defined`. Please help

**Comment by thodic** [comment]
I am also getting the same issue, maybe related to https://github.com/laravel/echo/pull/110. Using:

```
import Pusher from "pusher-js"
import VueEcho from 'vue-echo'

window.Pusher = Pusher;

Vue.use(VueEcho, {
    broadcaster: 'pusher',
    key: process.env.PUSHER_KEY,
})
```

I start getting `Uncaught You must pass your app key when you instantiate Pusher.`.

**Comment by thodic** [comment]
Turns out I was getting `Uncaught You must pass your app key when you instantiate Pusher.` because I wasn't setting `process.env.PUSHER_KEY` correctly. The above code should fix this issue, defining the key correctly the module installs correctly.  

But I am wondering with the changes in https://github.com/laravel/echo/pull/110 if there is a cleaner way to handle this in this module?

**Comment by salvationarinze** [comment]
It worked, man. Thanks
