### ISSUE TITLE
Context of this in callbacks

### ISSUE THREAD

**Issue by bradleybensmith** [happyDemon/vue-echo#6]
When using the ``echo`` callbacks, the context of ``this`` isn't the Vue instance.

**Comment by happyDemon** [comment]
@bram1028 
depending on how you define your callbacks it will act differently.
normally if you use an arrow function, `this` would be equal to the vm.

**Edit** I just noticed it does not take the VM as context, but rather a level up where the VM is defined. I'll see what I can do.

otherwise I would suggest making a var called `self` and assign `this` to it, which you can use without having to worry about the scope.

**Comment by happyDemon** [comment]
@bram1028 I've add a second parameter for locally registered event handlers, you can use that of trying to access `this`

**Comment by bradleybensmith** [comment]
Yah, I couldn't figure out the issue. Manually calling ``listen`` worked fine but no matter how I defined the callback in the ``echo`` options, it just wouldn't work. I'm also using the Vue single-file thing, so I'm sure that probably adds to the complexity.

Thanks for this update. Saves me some typing :)
